var statesData = {
   "Alabama":1,
   "Alaska":2,
   "Arizona":4,
   "Arkansas":5,
   "California":6,
   "Colorado":7,
   "Connecticut":8,
   "Delaware":9,
   "District of Columbia":10,
   "Florida":12,
   "Georgia":13,
   "Hawaii":15,
   "Idaho":16,
   "Illinois":17,
   "Indiana":18,
   "Iowa":19,
   "Kansas":20,
   "Kentucky":21,
   "Louisiana":22,
   "Maine":23,
   "Maryland":25,
   "Massachusetts":26,
   "Michigan":27,
   "Minnesota":28,
   "Mississippi":29,
   "Missouri":30,
   "Montana":31,
   "Nebraska":32,
   "Nevada":33,
   "New Hampshire":34,
   "New Jersey":35,
   "New Mexico":36,
   "New York":37,
   "North Carolina":38,
   "North Dakota":39,
   "Ohio":41,
   "Oklahoma":42,
   "Oregon":43,
   "Pennsylvania":45,
   "Rhode Island":47,
   "South Carolina":48,
   "South Dakota":49,
   "Tennessee":50,
   "Texas":51,
   "Utah":52,
   "Vermont":53,
   "Virginia":55,
   "Washington":56,
   "Wisconsin":58,
   "Wyoming":59,
   "United States":60,
   "West Virginia":61,
}

module.exports.statesData = statesData;
